server:
  port: 10002
spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      globalcors: # 解决跨域问题
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowCredentials: true
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          route-id-prefix: gateway-
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        port: 7777
        dashboard: 127.0.0.1:8888
      web-context-unify: false
      eager: true
  sleuth:
    sampler:
      # sleuth采样的百分比
      probability: 1.0
  zipkin:
    # zipkin的服务端地址
    base-url: http://127.0.0.1:9411
    # 将服务治理 当成一个url 而不是按服务名处理
    discovery-client-enabled: false
